apiVersion: v1
kind: Service
metadata:
  name: agones-gameserver
spec:
  type: LoadBalancer
  selector:
    agones.dev/gameserver: simple-game-server-2pr7n
  ports:
  - protocol: UDP
    port: 7654 # local port
    targetPort: 7654